import type { NextApiRequest, NextApiResponse } from "next";
import { NextResponse, NextRequest } from "next/server";
let cache: any[] = [];

const softDrinks = [
	{
		id: 1,
		productName: "coke zero",
		productSize: "30CL",
		productPrice: 350,
		productImage: "/svgs/coke.svg",
		productQuantity: 104,
	},
	{
		id: 2,
		productName: "yoghurt",
		productSize: "50CL",
		productPrice: 700,
		productImage: "/svgs/coke.svg",
		productQuantity: 35,
	},
	{
		id: 3,
		productName: "chivita",
		productSize: "35CL",
		productPrice: 800,
		productImage: "/svgs/coke.svg",
		productQuantity: 0,
	},
	{
		id: 4,
		productName: "cocacola",
		productSize: "30CL",
		productPrice: 350,
		productImage: "/svgs/coke.svg",
		productQuantity: 104,
	},
	{
		id: 5,
		productName: "fayrouz",
		productSize: "50CL",
		productPrice: 700,
		productImage: "/svgs/coke.svg",
		productQuantity: 35,
	},
	{
		id: 6,
		productName: "amstel malt",
		productSize: "35CL",
		productPrice: 800,
		productImage: "/svgs/coke.svg",
		productQuantity: 10,
	},
	{
		id: 7,
		productName: "chi exotic",
		productSize: "30CL",
		productPrice: 350,
		productImage: "/svgs/coke.svg",
		productQuantity: 104,
	},
	{
		id: 8,
		productName: "Sprite",
		productSize: "50CL",
		productPrice: 700,
		productImage: "/svgs/coke.svg",
		productQuantity: 35,
	},
	{
		id: 9,
		productName: "Fanta",
		productSize: "35CL",
		productPrice: 800,
		productImage: "/svgs/coke.svg",
		productQuantity: 10,
	},
	{
		id: 10,
		productName: "Hollandia",
		productSize: "30CL",
		productPrice: 350,
		productImage: "/svgs/coke.svg",
		productQuantity: 104,
	},
	{
		id: 11,
		productName: "Vitamilk",
		productSize: "50CL",
		productPrice: 700,
		productImage: "/svgs/coke.svg",
		productQuantity: 35,
	},
	{
		id: 12,
		productName: "smoothie",
		productSize: "35CL",
		productPrice: 800,
		productImage: "/svgs/coke.svg",
		productQuantity: 10,
	},
	{
		id: 13,
		productName: "cocktails",
		productSize: "35CL",
		productPrice: 1500,
		productImage: "/svgs/coke.svg",
		productQuantity: 10,
	},
	{
		id: 14,
		productName: "milkshake",
		productSize: "35CL",
		productPrice: 1200,
		productImage: "/svgs/coke.svg",
		productQuantity: 10,
	},
	{
		id: 15,
		productName: "pepsi",
		productSize: "35CL",
		productPrice: 500,
		productImage: "/svgs/coke.svg",
		productQuantity: 10,
	},
	{
		id: 16,
		productName: "tonic",
		productSize: "35CL",
		productPrice: 800,
		productImage: "/svgs/coke.svg",
		productQuantity: 10,
	},
];
const alcholicDrinks = [
	{
		id: 1,
		productName: "henessy",
		productSize: "30CL",
		productPrice: 350,
		productImage: "/svgs/alcohol_icon.svg",
		productQuantity: 104,
	},
	{
		id: 2,
		productName: "jameson",
		productSize: "50CL",
		productPrice: 700,
		productImage: "/svgs/alcohol_icon.svg",
		productQuantity: 35,
	},
	{
		id: 3,
		productName: "moet",
		productSize: "35CL",
		productPrice: 800,
		productImage: "/svgs/alcohol_icon.svg",
		productQuantity: 0,
	},
	{
		id: 4,
		productName: "remy martins",
		productSize: "30CL",
		productPrice: 350,
		productImage: "/svgs/alcohol_icon.svg",
		productQuantity: 104,
	},
	{
		id: 5,
		productName: "smirnoff",
		productSize: "50CL",
		productPrice: 700,
		productImage: "/svgs/alcohol_icon.svg",
		productQuantity: 35,
	},
	{
		id: 6,
		productName: "baileys",
		productSize: "35CL",
		productPrice: 800,
		productImage: "/svgs/alcohol_icon.svg",
		productQuantity: 10,
	},
	{
		id: 7,
		productName: "amarula",
		productSize: "30CL",
		productPrice: 350,
		productImage: "/svgs/alcohol_icon.svg",
		productQuantity: 104,
	},
	{
		id: 8,
		productName: "8pm",
		productSize: "50CL",
		productPrice: 700,
		productImage: "/svgs/alcohol_icon.svg",
		productQuantity: 35,
	},
	{
		id: 9,
		productName: "azul",
		productSize: "35CL",
		productPrice: 800,
		productImage: "/svgs/alcohol_icon.svg",
		productQuantity: 10,
	},
	{
		id: 10,
		productName: "captain morgan",
		productSize: "30CL",
		productPrice: 350,
		productImage: "/svgs/alcohol_icon.svg",
		productQuantity: 104,
	},
	{
		id: 11,
		productName: "four cousins",
		productSize: "50CL",
		productPrice: 700,
		productImage: "/svgs/alcohol_icon.svg",
		productQuantity: 35,
	},
	{
		id: 12,
		productName: "tequila",
		productSize: "35CL",
		productPrice: 800,
		productImage: "/svgs/alcohol_icon.svg",
		productQuantity: 10,
	},
	{
		id: 13,
		productName: "captain jack",
		productSize: "100CL",
		productPrice: 500,
		productImage: "/svgs/alcohol_icon.svg",
		productQuantity: 104,
	},
	{
		id: 14,
		productName: "mocktail",
		productSize: "100CL",
		productPrice: 500,
		productImage: "/svgs/alcohol_icon.svg",
		productQuantity: 104,
	},
	{
		id: 15,
		productName: "johnny walker",
		productSize: "100CL",
		productPrice: 500,
		productImage: "/svgs/alcohol_icon.svg",
		productQuantity: 104,
	},
	{
		id: 16,
		productName: "martini",
		productSize: "100CL",
		productPrice: 500,
		productImage: "/svgs/alcohol_icon.svg",
		productQuantity: 104,
	},
];
export default async function GET(request: Request) {
    try {
		const {
			query: { drinkType },
		} = request;
		const drinkArr = drinkType === "soft" ? softDrinks : alcholicDrinks;
		cache = drinkArr;
		new Response({ data: cache, success: true });
	} catch (error: any) {
		new Response({ data: null, success: false });
	}
}